# Generated by Django 5.0.6 on 2025-05-02 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_rename_city_region_city_id_alter_region_title'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractuser',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job.city'),
        ),
        migrations.AlterField(
            model_name='abstractuser',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job.region'),
        ),
    ]
