# Generated by Django 5.0.6 on 2025-03-14 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractuser',
            name='full_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='abstractuser',
            name='full_name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='abstractuser',
            name='full_name_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='abstractuser',
            name='full_name_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='abstractuser',
            name='gender',
            field=models.CharField(choices=[('Male', 'Erkak'), ('Female', 'Ayol')], default='Male', max_length=10),
        ),
        migrations.AlterField(
            model_name='abstractuser',
            name='role',
            field=models.CharField(choices=[('client', 'client'), ('worker', 'worker')], max_length=50),
        ),
    ]
