# Generated by Django 5.0.6 on 2025-08-26 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('job', '0001_initial'),
        ('users', '0002_client_worker'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Client',
            new_name='ClientProfile',
        ),
        migrations.RenameModel(
            old_name='Worker',
            new_name='WorkerProfile',
        ),
        migrations.AlterField(
            model_name='abstractuser',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AddConstraint(
            model_name='abstractuser',
            constraint=models.UniqueConstraint(fields=('phone', 'role'), name='unique_phone_role'),
        ),
    ]
