# Generated by Django 5.0.6 on 2025-03-19 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_abstractuser_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractuser',
            name='status',
            field=models.CharField(choices=[('idle', 'Boʻsh'), ('working', 'Ishlayapti'), ('waiting_confirmation', 'Tasdiqlashni kutmoqda'), ('completed', 'Yakunlandi'), ('active', 'Faol')], default='idle', max_length=20),
        ),
    ]
