# Generated by Django 4.2.10 on 2025-10-28 10:33

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_client_clientprofile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abstractuser',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='abstractuser',
            name='longitude',
        ),
        migrations.AddField(
            model_name='abstractuser',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(69.279759, 41.311081), srid=4326),
        ),
    ]
