# Generated by Django 5.0.6 on 2025-03-24 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_alter_region_city_id'),
        ('users', '0003_abstractuser_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractuser',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='job.city'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='abstractuser',
            name='phone',
            field=models.CharField(default=1, max_length=15, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='abstractuser',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='job.region'),
            preserve_default=False,
        ),
    ]
