# Generated by Django 4.2.10 on 2025-11-05 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_abstractuser_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractuser',
            name='pinfl',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
