# Generated by Django 4.2.10 on 2025-11-06 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_abstractuser_pinfl'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractuser',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
