# Generated by Django 4.2.10 on 2025-11-06 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_abstractuser_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractuser',
            name='phone',
            field=models.CharField(max_length=25),
        ),
    ]
