# Generated by Django 4.2.10 on 2025-11-07 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_abstractuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractuser',
            name='myid_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
