# Generated by Django 4.2.10 on 2025-11-19 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_abstractuser_myid_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=255)),
                ('status', models.CharField(default='pending', max_length=30)),
                ('card_id', models.CharField(blank=True, max_length=255, null=True)),
                ('pan', models.TextField(blank=True, null=True)),
                ('expiry', models.TextField(blank=True, null=True)),
                ('card_holder', models.TextField(blank=True, null=True)),
                ('phone', models.TextField(blank=True, null=True)),
                ('card_token', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=255)),
                ('amount', models.IntegerField()),
                ('account', django_cryptography.fields.encrypt(models.CharField(max_length=255))),
                ('store_id', django_cryptography.fields.encrypt(models.CharField(max_length=255))),
                ('terminal_id', django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=255, null=True))),
                ('status', models.CharField(default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
