# Generated by Django 4.2.10 on 2025-12-17 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_usercard_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercard',
            name='transaction_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
