# Generated by Django 5.0.6 on 2025-03-25 06:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        ('job', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='accepted_workers',
            field=models.ManyToManyField(blank=True, related_name='accepted_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.city'),
        ),
        migrations.AddField(
            model_name='order',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='finished_workers',
            field=models.ManyToManyField(blank=True, related_name='finished_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='job_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='job.categoryjob'),
        ),
        migrations.AddField(
            model_name='order',
            name='job_id',
            field=models.ManyToManyField(blank=True, to='job.job'),
        ),
        migrations.AddField(
            model_name='order',
            name='notified_workers',
            field=models.ManyToManyField(blank=True, related_name='notified_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.region'),
        ),
        migrations.AddField(
            model_name='order',
            name='rejected_workers',
            field=models.ManyToManyField(blank=True, related_name='rejected_workers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_as_worker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tarifharidi',
            name='tarif_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='client.clienttarif'),
        ),
        migrations.AddField(
            model_name='tarifharidi',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_harid', to=settings.AUTH_USER_MODEL),
        ),
    ]
