# Generated by Django 5.0.6 on 2025-03-19 03:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_alter_order_city_alter_order_region'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='finished_workers',
            field=models.ManyToManyField(blank=True, related_name='finished_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='notified_workers',
            field=models.ManyToManyField(blank=True, related_name='notified_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='rejected_workers',
            field=models.ManyToManyField(blank=True, related_name='rejected_workers', to=settings.AUTH_USER_MODEL),
        ),
    ]
