# Generated by Django 5.0.6 on 2025-03-24 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_rename_is_finish_order_client_is_finished_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('stable', 'Stable'), ('success', 'Success'), ('in_progress', 'In_progress'), ('cancel_client', 'Cancel by Client'), ('cancel_worker', 'Cancel by Worker')], default='stable', max_length=20),
        ),
    ]
