# Generated by Django 5.0.6 on 2025-05-02 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='region',
            old_name='city',
            new_name='city_id',
        ),
        migrations.AlterField(
            model_name='region',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='City Name'),
        ),
    ]
