# Generated by Django 5.0.6 on 2025-03-24 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='city_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='job.city'),
            preserve_default=False,
        ),
    ]
